version: '3.9'

services:
  barotrauma:
    build: ./Barotrauma
    container_name: Barotrauma
    environment:
      BAR_SETTING_public: '"True"'
      BAR_SETTING_name: '${BAR_SETTING_NAME}'
      BAR_SETTING_password: '"${BAR_SETTING_PASSWORD}"'
      BAR_SETTING_port: '"${BAR_SETTING_PORT}"'
      BAR_SETTING_port: '"${BAR_SETTING_QUERYPORT}"'
    volumes:
      - "./barotrauma/subs:/Submarines"
      - "./barotrauma/mods:/Mods"
      - "./barotrauma/saves:/Saves"
    ports:
      - target: ${BAR_SETTING_PORT}
        published: ${BAR_SETTING_PORT}
        protocol: udp
      - target: ${BAR_SETTING_QUERYPORT}
        published: ${BAR_SETTING_QUERYPORT}
        protocol: udp
